$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/ViaBrowser)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/SimpleGallery)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/app/SimpleCalender)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/product/priv-app/WeatherIcons)
$(call add-clean-step, rm -rf $(PRODUCT_OUT)/system/system_ext/priv-app/OmniJaws)
